.gitignore
build.gradle
src/main/java/uk/gov/justice/digital/hmpps/keyworker/controllers/KeyworkerServiceController.java
src/main/java/uk/gov/justice/digital/hmpps/keyworker/dto/AllocationType.java
src/main/java/uk/gov/justice/digital/hmpps/keyworker/dto/AllocationsRequestDto.java
src/main/java/uk/gov/justice/digital/hmpps/keyworker/dto/KeyworkerAllocationDto.java
src/main/java/uk/gov/justice/digital/hmpps/keyworker/dto/KeyworkerDto.java
src/main/java/uk/gov/justice/digital/hmpps/keyworker/dto/PageDto.java
src/main/java/uk/gov/justice/digital/hmpps/keyworker/dto/SortOrder.java
src/main/java/uk/gov/justice/digital/hmpps/keyworker/model/OffenderKeyworker.java
src/main/java/uk/gov/justice/digital/hmpps/keyworker/repository/OffenderKeyworkerRepository.java
src/main/java/uk/gov/justice/digital/hmpps/keyworker/services/KeyworkerService.java
src/main/resources/application.yml

keyworker-service
First cut:
getAvailableKeyworkers
getKeyworkerAllocations

NN-563: Implement all existing Key worker API endpoint in 

---

build.gradle
src/main/java/uk/gov/justice/digital/hmpps/keyworker/KeyworkerApplication.java
src/main/java/uk/gov/justice/digital/hmpps/keyworker/controllers/KeyworkerServiceController.java
src/main/java/uk/gov/justice/digital/hmpps/keyworker/dto/AllocationType.java
src/main/java/uk/gov/justice/digital/hmpps/keyworker/dto/AllocationsFilterDto.java
src/main/java/uk/gov/justice/digital/hmpps/keyworker/dto/KeyworkerAllocationDetailsDto.java
src/main/java/uk/gov/justice/digital/hmpps/keyworker/dto/KeyworkerAllocationDto.java
src/main/java/uk/gov/justice/digital/hmpps/keyworker/model/AllocationType.java
src/main/java/uk/gov/justice/digital/hmpps/keyworker/model/Audit.java
src/main/java/uk/gov/justice/digital/hmpps/keyworker/model/CreateUpdate.java
src/main/java/uk/gov/justice/digital/hmpps/keyworker/model/OffenderKeyworker.java
src/main/java/uk/gov/justice/digital/hmpps/keyworker/repository/OffenderKeyworkerRepository.java
src/main/java/uk/gov/justice/digital/hmpps/keyworker/repository/package-info.java
src/main/resources/.gitignore
src/main/resources/application.properties
src/main/resources/application.yml
src/main/resources/db/migration/V1_1__offender_key_worker.sql
src/main/resources/db/migration/V1_2__hibernate_id_sequence.sql
src/test/java/uk/gov/justice/digital/hmpps/keyworker/repository/OffenderKeyworkerRepositoryTest.java

flyway, a Hibernate mapped OffenderKeyworker entity and some basic
integration tests for the mapping and repository.

NN-556 First attempt at creating an OFFENDER_KEY_WORKER table using

---

build.gradle
src/main/java/uk/gov/justice/digital/hmpps/keyworker/dto/KeyworkerAllocationDto.java
src/main/java/uk/gov/justice/digital/hmpps/keyworker/dto/KeyworkerDto.java
src/main/java/uk/gov/justice/digital/hmpps/keyworker/exception/AllocationException.java
src/main/java/uk/gov/justice/digital/hmpps/keyworker/model/AllocationReason.java
src/main/java/uk/gov/justice/digital/hmpps/keyworker/repository/OffenderKeyworkerRepository.java
src/main/java/uk/gov/justice/digital/hmpps/keyworker/services/KeyworkerPool.java
src/main/java/uk/gov/justice/digital/hmpps/keyworker/services/KeyworkerService.java
src/test/java/uk/gov/justice/digital/hmpps/keyworker/services/KeyworkerPoolTest.java
src/test/java/uk/gov/justice/digital/hmpps/keyworker/services/KeyworkerTestHelper.java

This is an initial commit. It includes KeyworkerPool and associated unit test class. It also fixes the auto-allocate API.

NN-561: Implement auto-allocation service in new Key worker component

---

src/main/java/uk/gov/justice/digital/hmpps/keyworker/services/KeyworkerService.java

I've added @lbennett-moj and @steverendell  to this role in PVB dev db

Restrict service calls to have KW_ADMIN role

---

src/main/java/uk/gov/justice/digital/hmpps/keyworker/controllers/KeyworkerServiceController.java
src/main/java/uk/gov/justice/digital/hmpps/keyworker/dto/KeyworkerUpdateDto.java
src/main/java/uk/gov/justice/digital/hmpps/keyworker/services/KeyworkerService.java
src/test/java/uk/gov/justice/digital/hmpps/keyworker/services/KeyworkerServiceTest.java

* New endpoint to allow the creation or updating of keyworker 
* Added dto and services to facilitate create/update
* Added tests

Update keyworker service

---

src/main/java/uk/gov/justice/digital/hmpps/keyworker/dto/OffenderLocationDto.java
src/main/java/uk/gov/justice/digital/hmpps/keyworker/dto/OffenderSummaryDto.java
src/main/java/uk/gov/justice/digital/hmpps/keyworker/services/KeyworkerService.java
src/test/java/uk/gov/justice/digital/hmpps/keyworker/services/KeyworkerServiceTest.java

ordering key workers by number allocated and fix for missing internal location

NN_5 add ordering to get available keyworkers

---

src/main/java/uk/gov/justice/digital/hmpps/keyworker/controllers/KeyworkerServiceController.java
src/main/java/uk/gov/justice/digital/hmpps/keyworker/services/KeyworkerMigrationService.java
src/main/java/uk/gov/justice/digital/hmpps/keyworker/services/KeyworkerPool.java
src/main/java/uk/gov/justice/digital/hmpps/keyworker/services/KeyworkerService.java
src/main/java/uk/gov/justice/digital/hmpps/keyworker/services/NomisService.java
src/main/java/uk/gov/justice/digital/hmpps/keyworker/services/RestCallHelper.java
src/main/java/uk/gov/justice/digital/hmpps/keyworker/utils/ConversionHelper.java
src/test/java/uk/gov/justice/digital/hmpps/keyworker/services/KeyworkerMigrationServiceTest.java
src/test/java/uk/gov/justice/digital/hmpps/keyworker/services/KeyworkerServiceTest.java
src/test/java/uk/gov/justice/digital/hmpps/keyworker/services/KeyworkerTestHelper.java

Add an Nomis Service to abstract away the Elite2API calls
Make the Elite2APISource a simple helper.

Remove the Elite2APISource abstract class

---

src/main/java/uk/gov/justice/digital/hmpps/keyworker/dto/KeyworkerDto.java
src/main/java/uk/gov/justice/digital/hmpps/keyworker/services/KeyworkerService.java
src/test/java/uk/gov/justice/digital/hmpps/keyworker/services/KeyworkerServiceTest.java

Sort within each capacity band

NN-765 Remove INACTIVE from drop down list of available KW to allocation

---

src/main/java/uk/gov/justice/digital/hmpps/keyworker/dto/StaffLocationRoleDto.java
src/main/java/uk/gov/justice/digital/hmpps/keyworker/services/KeyworkerService.java
src/main/java/uk/gov/justice/digital/hmpps/keyworker/services/NomisService.java

Only return a staff member once even if they have mulitple position per role
Don't error when multiple roles are returned for 1 staff member

NN-770 Multiple Staff Roles need to be handled correctly

---

src/main/java/uk/gov/justice/digital/hmpps/keyworker/controllers/KeyworkerServiceController.java
src/main/java/uk/gov/justice/digital/hmpps/keyworker/dto/CaseNoteUsageDto.java
src/main/java/uk/gov/justice/digital/hmpps/keyworker/dto/CaseNoteUsageRequest.java
src/main/java/uk/gov/justice/digital/hmpps/keyworker/dto/KeyworkerDto.java
src/main/java/uk/gov/justice/digital/hmpps/keyworker/services/KeyworkerService.java
src/main/java/uk/gov/justice/digital/hmpps/keyworker/services/NomisService.java
src/main/java/uk/gov/justice/digital/hmpps/keyworker/services/NomisServiceImpl.java
src/main/java/uk/gov/justice/digital/hmpps/keyworker/services/RestCallHelper.java
src/test/groovy/uk/gov/justice/digital/hmpps/keyworker/integration/mockApis/Elite2Api.groovy
src/test/groovy/uk/gov/justice/digital/hmpps/keyworker/integration/mockResponses/CaseNoteUsageListStub.groovy
src/test/groovy/uk/gov/justice/digital/hmpps/keyworker/integration/specs/KeyworkerSearchSpecification.groovy
src/test/java/uk/gov/justice/digital/hmpps/keyworker/services/KeyworkerAutoAllocationServiceTest.java
src/test/java/uk/gov/justice/digital/hmpps/keyworker/services/KeyworkerServiceTest.java

Filter out non active from manual assignment

NN-963 Add case note counting for active keyworkers

---

src/main/java/uk/gov/justice/digital/hmpps/keyworker/dto/OffenderKeyWorkerHistory.java
src/main/java/uk/gov/justice/digital/hmpps/keyworker/dto/PrisonerDetail.java
src/main/java/uk/gov/justice/digital/hmpps/keyworker/services/KeyworkerService.java
src/main/java/uk/gov/justice/digital/hmpps/keyworker/services/NomisService.java
src/main/java/uk/gov/justice/digital/hmpps/keyworker/services/NomisServiceImpl.java
src/main/java/uk/gov/justice/digital/hmpps/keyworker/utils/ConversionHelper.java
src/main/resources/application.properties
src/main/resources/logback-spring.xml
src/test/groovy/uk/gov/justice/digital/hmpps/keyworker/integration/mockApis/Elite2Api.groovy
src/test/groovy/uk/gov/justice/digital/hmpps/keyworker/integration/mockResponses/OffenderLocationDtoListStub.groovy
src/test/groovy/uk/gov/justice/digital/hmpps/keyworker/integration/specs/OffenderKeyworkerHistorySpecification.groovy
src/test/java/uk/gov/justice/digital/hmpps/keyworker/services/KeyworkerServiceTest.java
src/test/java/uk/gov/justice/digital/hmpps/keyworker/services/KeyworkerTestHelper.java

Nn 1045 Return Legacy Allocations in OMIC UI

---

src/main/java/uk/gov/justice/digital/hmpps/keyworker/controllers/KeyworkerStatsController.java
src/main/java/uk/gov/justice/digital/hmpps/keyworker/services/KeyworkerStatsService.java
src/test/groovy/uk/gov/justice/digital/hmpps/keyworker/integration/mockApis/Elite2Api.groovy
src/test/groovy/uk/gov/justice/digital/hmpps/keyworker/integration/specs/KeyworkerStatsSpecification.groovy
src/test/java/uk/gov/justice/digital/hmpps/keyworker/services/KeyworkerStatsServiceTest.java

- Renamed a couple of methods to make them more readable
- Simplified the call to case note usage counts
- Tweaked tests

NN-1238 Key worker stats API

---

src/main/java/uk/gov/justice/digital/hmpps/keyworker/services/NomisService.java
src/main/java/uk/gov/justice/digital/hmpps/keyworker/services/NomisServiceImpl.java
src/main/java/uk/gov/justice/digital/hmpps/keyworker/services/ReconciliationService.java
src/main/java/uk/gov/justice/digital/hmpps/keyworker/services/RestCallHelper.java
src/test/java/uk/gov/justice/digital/hmpps/keyworker/services/ReconciliationServiceTest.java

- deallocation cannot get prisoner statuses
- getting all prisons fails so no users are enabled.

NN-1871 - Bug Fixes

---

src/main/java/uk/gov/justice/digital/hmpps/keyworker/security/AuthAwareAuthenticationToken.java

I removed this earlier because I couldn't reproduce the issue it caused.  Putting it back in because the issue is currently presenting on t3.

DT-611 Fix machine to machine auth

---

helm_deploy/keyworker-api/templates/deployment.yaml
helm_deploy/keyworker-api/templates/ingress.yaml

Reverts ministryofjustice/keyworker-api#249

Revert "DT-917: Switch out deprecated APIs"

---

helm_deploy/keyworker-api/templates/deployment.yaml
helm_deploy/keyworker-api/templates/ingress.yaml

Reverts ministryofjustice/keyworker-api#251

Revert "Revert "DT-917: Switch out deprecated APIs""

---

.circleci/config.yml
README.md
build.gradle.kts
docker-compose-all.yml
docker-compose.yml
src/main/java/uk/gov/justice/digital/hmpps/keyworker/config/VersionOutputter.kt
src/main/resources/logback-spring.xml

updated docker compose to pull images from quay
switched Master to Main
and upgraded springboot

DT-851: updated logging and added version for app insights

---

src/main/java/uk/gov/justice/digital/hmpps/keyworker/controllers/ControllerAdvice.java

Exceptions appear in App Insights but not founds are expected, not exceptional

DT-941 Don't log 404 exceptions just log the details

---

helm_deploy/keyworker-api/templates/ingress.yaml

Reverts ministryofjustice/keyworker-api#266

Revert "NN-2906: Use namespace for ingress class"

---

helm_deploy/keyworker-api/templates/_envs.tpl
helm_deploy/values-dev.yaml
src/main/java/uk/gov/justice/digital/hmpps/keyworker/services/KeyworkerAutoAllocationService.java
src/main/java/uk/gov/justice/digital/hmpps/keyworker/services/MoicService.java
src/main/resources/application.properties
src/test/java/uk/gov/justice/digital/hmpps/keyworker/services/KeyworkerAutoAllocationServiceTest.java

At the moment it's using a dummy implementation of the MOIC service, it contains some hard coded offender numbers so that we can start testing the impact of skipping offenders. 
Once the MOIC team are ready we will swap out the implementation, add health checks etc.

NN-3109 initial bit of work to test for skipping complex offenders

---

build.gradle.kts

Reverts ministryofjustice/keyworker-api#314

Revert "NN-3207: Camel direct routing needs explicit library"

---

helm_deploy/keyworker-api/values.yaml
src/main/resources/application.yml

Reverts ministryofjustice/keyworker-api#411

Revert "NN-4278 sensible naming and defaults"

---

helm_deploy/keyworker-api/Chart.yaml
helm_deploy/keyworker-api/templates/_envs.tpl
helm_deploy/keyworker-api/templates/deployment.yaml
helm_deploy/keyworker-api/templates/service.yaml
helm_deploy/keyworker-api/values.yaml
helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml
src/main/resources/application-postgres.properties
src/main/resources/application.properties
src/main/resources/application.yml

Reverts ministryofjustice/keyworker-api#410

Revert "NN-4278 part 2"

---

helm_deploy/values-dev.yaml

Reverts ministryofjustice/keyworker-api#420

Revert "Exclude allowlist in dev and fix ingress definition"

---

.circleci/config.yml
build.gradle.kts
gradle/wrapper/gradle-wrapper.properties
helm_deploy/keyworker-api/Chart.yaml

https://dsdmoj.atlassian.net/browse/NN-4627

NN-4627: bump dependencies and versions

---

build.gradle.kts
helm_deploy/keyworker-api/Chart.yaml
helm_deploy/keyworker-api/values.yaml

https://dsdmoj.atlassian.net/browse/NN-4730

NN-4730: bump helm charts and deps

---

helm_deploy/values-prod.yaml

https://dsdmoj.atlassian.net/browse/NN-4706

NN-4706: fix indentation and move above allowList

---

helm_deploy/values-preprod.yaml

https://dsdmoj.atlassian.net/browse/NN-5134

NN-5134: scale PreProd services from 4 to 2

---

helm_deploy/keyworker-api/values.yaml
helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

https://dsdmoj.atlassian.net/browse/NN-5154

NN-5154: use IRSA to connect to SQS and SNS - dev

---

helm_deploy/keyworker-api/values.yaml
helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

https://dsdmoj.atlassian.net/browse/NN-5154

NN-5154: use IRSA to connect to SQS and SNS- PreProd and Prod

---

helm_deploy/values-dev.yaml

https://dsdmoj.atlassian.net/browse/NN-5154

NN-5154: fix dev helm config

---

build.gradle.kts
renovate.json

This reverts commit d552a237931671070931daa01449ebcd06e0200f.

Revert "Attempt using camel-health to display route status on /health endpoint (#464)"

---

build.gradle.kts

https://dsdmoj.atlassian.net/browse/NN-5031
This failed after merging #469 - see https://app.circleci.com/pipelines/github/ministryofjustice/keyworker-api/2195/workflows/0dcee60c-5bba-486a-b0a9-15ff00d8dabf/jobs/6147/parallel-runs/0/steps/0-109

NN-5031: attempt to fix gradle task bootJar

---

src/main/java/uk/gov/justice/digital/hmpps/keyworker/services/NomisServiceImpl.java
src/main/java/uk/gov/justice/digital/hmpps/keyworker/services/RestCallHelper.java

SDIT-1184 KeyWorkerResource

---

src/main/java/uk/gov/justice/digital/hmpps/keyworker/services/NomisServiceImpl.java

use client id for prison-api call

SDIT-1384 StaffResource

---

.circleci/config.yml

Update config.yml to disable Slack notifications

MIA-136: Disable Slack notifications for Prod deployments
